### ISSUE TITLE
@elderjs/plugin-images - output path corrupted on windows

### ISSUE THREAD

**Issue by meigo** [Elderjs/plugins#28]
Getting this kind of error messages:

```console
Error: Hook: "processImages" threw an error: ENOENT: no such file or directory, copyfile 'D:/Projects/elderjs-images/images/image.jpg' -> 'D:\Projects\elderjs-images\public\images\D:\Projects\elderjs-imagesimage.jpg'

...

at async D:\Projects\elderjs-images\node_modules\@elderjs\elderjs\build\Elder.js:297:13 {
	errno: -4058,
	syscall: 'copyfile',
	code: 'ENOENT',
	path: 'D:/Projects/Kadastiku/web/elder/elderjs-images/images/image.jpg',
	dest: 'D:\\Projects\\elderjs-images\\public\\images\\D:\\Projects\\elderjs-imagesimage.jpg'
}
```

**Comment by nickreese** [comment]
Should be fixed in `0.1.9` that was just pushed. 

Cross platform `fs` is one of the worst parts about node lol. 

Let me know if it doesn't work.

**Comment by meigo** [comment]
Thanks Nick. No build time errors anymore, everything's generated nicely, just the relative path is still incorrect, and only the placeholder image is shown at runtime.

```json
{"/images/image.jpg":{
	"width":1920,
	"height":1137,
	"format":"jpeg",
	"original":"/images/image.jpg",
	"sizes":[{
		"width":1280,
		"height":758,
		"format":"webp",
		"relative":"/images/imageD:\\Projects\\elderjs-images\\public\\images\\image-ejs-1280.webp",
		"scale":1,
		"cache":"D:\\Projects\\elderjs-images\\images\\sizes\\image-ejs-1280.webp",
		"public":"D:\\Projects\\elderjs-images\\public\\images\\image-ejs-1280.webp"},
```

Using default configuration btw.

**Comment by meigo** [comment]
Problem seems to be here:

```js
// getPrefix.js 
return fileWithoutExt + publicPrefix.split(fileWithoutExt).pop();
```
Mixed forward- and backslashes on windows and split operation doesn't do anything:
 
```js
fileWithoutExt = '/images/image'
publicPrefix = 'D:\Projects\elderjs-images\public\images\image'
```

**Comment by nickreese** [comment]
This will be fixed in the next release.
